### ISSUE TITLE
update the README.md file

### ISSUE THREAD

**Issue by peculiaruc** [NICUB-Open-Source-Community/LEMAs#2]

**Comment by Wesley-Perrang** [comment]
Hey Peculiaruc, what do you mean by updating the README file?

**Comment by peculiaruc** [comment]
The ReadMe is not up to standard, it should have instructions on how new contributors can get started in contributing to this project. 

Technologies to be used 

Link to contributing.md

**Comment by Wesley-Perrang** [comment]
Ok thank you

**Comment by peculiaruc** [comment]
> Ok thank you

@Wesley-Perrang  If you are willing to contribute to the Backend of an open-source project, let me know. The project has some contributors already and it is a real-life project.  Thats if ou are good on the Backend and you are interested
