### ISSUE TITLE
Create the Sign Up Form

### ISSUE THREAD

**Issue by peculiaruc** [NICUB-Open-Source-Community/LEMAs#4]
![image](https://github.com/HelCoders-Open-Source-Community/LEMAs/assets/35475543/25c122b9-48db-4b82-ae73-57000911ccda)

**Comment by NateOs** [comment]
I am going to take on this one, if it's okay, with you, Is there anything I should be aware of?

**Comment by peculiaruc** [comment]
> I am going to take on this one, if it's okay, with you, Is there anything I should be aware of?

none, go ahead

**Comment by NateOs** [comment]
Hi @peculiaruc is there a figma that i can refer to for this page, I don't wanna be eyeballing...

**Comment by peculiaruc** [comment]
> Hi @peculiaruc is there a figma that i can refer to for this page, I don't wanna be eyeballing...

Sure, I have shared the figma with you. Kindly confirm that you got it.

**Comment by NateOs** [comment]
@peculiaruc just made a PR for this
